model_name: "dimenet++"

emb_size: 128
out_emb_size: 256
int_emb_size: 64
basis_emb_size: 8
num_blocks: 4

num_spherical: 7
num_radial: 6
output_init: 'GlorotOrthogonal'  # 'zeros' for mu, homo, lumo, and zpve; 'GlorotOrthogonal' for alpha, R2, U0, U, H, G, and Cv

extensive: True
cutoff: 7.0
envelope_exponent: 5

num_before_skip: 1
num_after_skip: 2
num_dense_output: 3

num_train: 78822
# num_train: 788
num_valid: 9852
data_seed: 42
dataset: "data/dye_train.npz"
logdir: "."

num_steps: 3000000
ema_decay: 0.999

learning_rate: 0.001
warmup_steps: 3000
decay_rate: 0.01
decay_steps: 4000000

batch_size: 8
evaluation_interval: 10000
save_interval: 10000
restart: None
comment: "final"
targets: ['homo', 'lumo']  # ['mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv']
